### ISSUE TITLE
Houseprint json not downloadable

### ISSUE THREAD

**Issue by m-f1549** [opengridcc/website#115]
Houseprint (.json) file on the website doesn't download but opens in the browser.

**Comment by saroele** [comment]
can you right-click on the link and select something like: 'download link
as' ?

**Comment by JrtPec** [comment]
Sure. But it's pretty easy to have images, pdf's and notebooks open in the browser, while other filetypes are downloaded.

**Comment by Ryton** [comment]
Also, %run cachehouseprint locally from the houseprintdemo notebook
creates an error, something about "get_sensor_list" function not existing (will post error trace later today). The hp object was generated correctly though.

**Comment by Ryton** [comment]
As promised, see below.

I thought i updated everything, but maybe i'm using a file in another directory. Is there a way to check which library directory is loaded?

<code>%run cache_anonymous_houseprint.py</code>
error trace:
<code>Houseprint parsing complete

---

AttributeError                            Traceback (most recent call last)
...path...\cache_anonymous_houseprint.py in <module>()
     18 
     19 hp = Houseprint()
---> 20 all_sensordata = hp.get_all_fluksosensors()
     21 print('Sensor data fetched')
     22 

AttributeError: 'Houseprint' object has no attribute 'get_all_fluksosensors'
</code>

**Comment by JrtPec** [comment]
Seems to me like you're running an older version of the demo notebook.

Sometime in 2015 we've drastically rewritten the Houseprint code to make it more generic and useful, so now you can do `hp.get_sensors()` or `hp.get_sensors(sensortype='electricity')`, but you can also just ask the houseprint object directly for the data you need, like `hp.get_data(sensortype='gas')`.

The current version of Demo_houseprint should explain everything, it is in opengrid/notebooks/Demo/Demo_houseprint.ipynb
