### ISSUE TITLE
New homepage

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#15]
I suggest moving the list of all fluksos to a second page, and have a home page with an explanation of the project, what things to expect on the website, link to the github page etc...

Does anybody want to 'design' such a page? Perhaps start with writing a little introduction text...

**Comment by saroele** [comment]
Fully agree, was on my mental list.  I'm happy to try this, would be a good intro to flask.  But I'm not against anyone else giving it a shot.

**Comment by JrtPec** [comment]
@WolfBerwouts I saw you've committed a new homepage, so I guess we can close this?

**Comment by saroele** [comment]
I like this!  And in order to keep it SMART, let's close this issue and discuss the content of the homepage in #23
