### ISSUE TITLE
Download to csv

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#24]
This was already discussed in https://github.com/opengridcc/opengrid/issues/75.
I'm working on it in a separate branch

**Comment by JrtPec** [comment]
I'm reopening this issue because the connection to the tmpo database is not working on the server. I have no time to debug right now. I however have a feeling where the problem may lie: perhaps there is some backend process which is continuously connected to tmpo? @saroele can you weigh in on this?

Until we can figure out some new kind of on-server data storage, it might be a good idea to only let back-end processes be connected to the tmpo when they need to, see opengridcc/opengrid#99

**Comment by saroele** [comment]
I'll have a look. May take a few days till I find time :-(
