### ISSUE TITLE
Include Fork me on GitHub banner

### ISSUE THREAD

**Issue by kdebrab** [opengridcc/website#29]
with link to opengridcc/opengrid repository

**Comment by JrtPec** [comment]
Merged #41

**Comment by JrtPec** [comment]
I'm reopening this issue because I noticed that when you display the website on a smaller screen, the navbar collapses into a single button in the top right, which you cannot click because the banner is laid over it. I can try putting a banner in the top left corner, but if that impedes some functionality I'm out of ideas.

**Comment by rubenbaetens** [comment]
Can't you force to get the single button top-left next to the logo when shown on smaller screens ?

**Comment by JrtPec** [comment]
Probably. Perhaps someone with some more knowledge on CSS and Bootstrap could weigh in on this.

**Comment by GMathyssen** [comment]
I will look into it

**Comment by JrtPec** [comment]
Additional bug I noticed: The `flash` messages have this little `x` button which you can use to close the div, but right now the button is hidden under the banner. (It doesn't look like it, but you can't click it).

**Comment by GMathyssen** [comment]
I can make the fork banner jump to the left (of right, but not so ideal for mobile) bottom corner of the page for mobile. Or maybe just move the thing there definitely?

**Comment by JrtPec** [comment]
Moving it to the bottom might solve all problems...

**Comment by GMathyssen** [comment]
I don't get the flash messages? Or not for the website that's now on-line...

**Comment by JrtPec** [comment]
Since we removed the separate sensor pages last Tuesday there are no more 'graph not found' errors... Try forcing a 404 error, that should display one too: go to www.opengrid.be/blablabla

**Comment by GMathyssen** [comment]
It is moved to the bottom left corner as a test. Feel free to give any comment

**Comment by JrtPec** [comment]
Fixed the link to the image, should have been `static/images/...`

It appears on the bottom left, but it appears at the bottom of the page, while it should be sticking to the bottom of the screen. Probably something to do with relative vs. absolute. Perhaps this screenshot clarifies things:
![screen shot 2016-02-12 at 00 14 39](https://cloud.githubusercontent.com/assets/4570408/12994119/84682cd8-d11e-11e5-900c-3aaa9548877f.png)

**Comment by JrtPec** [comment]
This is when I resized the page. I think the banner ought to be moving up with the window.
![screen shot 2016-02-12 at 00 21 59](https://cloud.githubusercontent.com/assets/4570408/12994160/c2af6600-d11e-11e5-88fa-a266e5f9535d.png)

**Comment by GMathyssen** [comment]
True, on it

**Comment by GMathyssen** [comment]
This might do the trick. Sorry that I can't test it myself, working on that!

**Comment by JrtPec** [comment]
It still looks the same...

**Comment by GMathyssen** [comment]
Banner in the left bottom wasn't so good for mobile, so I did the original idea: banner in top right, and for mobile just a button in the navbar.

**Comment by JrtPec** [comment]
Looks great! Tested on iPhone, looks great too.
One issue: the banner collapses into the navbar, but the span remains on top of the menu button. See screenshot.
![screen shot 2016-02-15 at 21 10 16](https://cloud.githubusercontent.com/assets/4570408/13059174/b2bf1eae-d428-11e5-8bbd-7792e50f7ebd.png)

**Comment by saroele** [comment]
ja gert, Jan is je wel tot het uiterste aan het drijven :)

**Comment by GMathyssen** [comment]
:) Mja, my mistake, I just have to test my work better. It is fixed!

**Comment by JrtPec** [comment]
:+1:
