### ISSUE TITLE
Add info to Wiki on how to run the website offline

### ISSUE THREAD

**Issue by WolfBerwouts** [opengridcc/website#34]
- Which packages do you need to run website offline: Flask, Flask-WTF?
- Specific data to load?

Jan, could you check on this?

Thanks

**Comment by JrtPec** [comment]
There is a `requirements.txt`, specific for the website. `Flask-WTF` needed to be added, but I see this has since been done :+1: 

If you want to load figures locally, you need to refer to their directory in `opengrid.cfg`. Ideally, this path points to the same folder where the back-end analyses drop their results. This might be a hassle, so we could include a small `mock_images` folder or something?

**Comment by saroele** [comment]
The site is for ourselves, I guess we can expect all devs to have an operational opengrid configuration? So I wouldn't bother with mock images.  Unless this is a problem for development now?

**Comment by GMathyssen** [comment]
Guys, I also have trouble with running the website locally. requirements.txt from the website and opengrid are installed, .cfg's are ok, pulled measurement data and still nothing.
I do have to run it with "python website.py"? Or am I missing something?

**Comment by GMathyssen** [comment]
Ah, I always get this error: IOError: [Errno 2] No such file or directory: 'cache_hp.hp'

**Comment by saroele** [comment]
Hi,
The site tries to load the houseprint from google docs, but if that doesn"'t work, it uses a cached houseprint.  We should add a default version of the cache_hp.hp in the repo. 

I'll send you the file in a mail and also add it to the repository.

**Comment by GMathyssen** [comment]
Thanks!

**Comment by saroele** [comment]
You'll need also to put a few lines in an opengrid.cfg file.  There's an opengrid.cfg.example to start from.  To give you an idea, mine looks like this:

```
[data]
folder: /mnt/data/work/opengrid/data

[backend]
#opengrid: path to opengrid source code
figures: /mnt/data/work/opengrid/data/figures

[env]
type: dev
```

As I have the path to my source code in my environment variable PYTHONPATH, I did not specify it again in this file.  I have make another small change to website.py that I will push in a minute: when you have the path to opengrid on your PYTHONPATH (or opengrid is installed with `pip install opengrid` you don't have to specify the backend/opengrid line.

**Comment by wouterh** [comment]
Don't put it in the repo! It contains flukso tokens! These should not be in
a public repository!

Op ma 8 feb. 2016 22:49 schreef saroele notifications@github.com:

**Comment by saroele** [comment]
I see your point.  But on the website we allow (anyone) to download the
measurements as csv. That's exactly the same (anonymous) data.

I'll remove the file,  but if you're concerned about the data,  we need a
discussion about how to share it.  Do we share the data anonymously for
research purposes?
Op 9 feb. 2016 06:57 schreef "Wouter Horré" notifications@github.com:

**Comment by wouterh** [comment]
It's too late then, once it's in git, it is in git forever (unless you do some very nasty history rewriting).

Flukso API tokens are like passwords. Putting these in the open is, imo, something else than sharing anonymous data...

**Comment by saroele** [comment]
I'm sorry, my mistake.  I think however that I was able to rewrite the history.  I hope that doesn't cause any problems for other website developers?  Let me know if you can't pull anymore. 

Sorry for the mess, i'll be more attentive.

**Comment by GMathyssen** [comment]
Can someone please check it, just to be sure: https://github.com/opengridcc/website/wiki/GettingStarted

**Comment by saroele** [comment]
Thanks for this initiative. I think we should explain the different entries in the opengrid.cfg file, so I will reopen this so we don't forget it.
