### ISSUE TITLE
Standby graph

### ISSUE THREAD

**Issue by rubenbaetens** [opengridcc/website#36]
I'll update the standby graphs of opengrid.be to look better, and include an external reference for it. That is, not only show a boxplot of the current fluksos but also add e.g. a EU-27 average as reference.

@saroele was there any reason why it's split up in 'horizontal' and 'vertikal'. The vertikal lacks any legend actually.

**Comment by saroele** [comment]
Nice, I think I can use some help in pimping the graphs.  But first I have to make them run again, based on the caching mechanism.  

So the diff between vertical and horizontal is just the layout and concept.  We discussed if bar graphs are the right concept.  They are probably too complicated for non-technical users.  So just low-medium-high lines on a graph may be better.  We wanted to create a green/orange/red surface or something similar.  I agree that this could be a nice visualisation, and not too technical. 

I think this issue should be on the opengrid repo however ;-)

**Comment by rubenbaetens** [comment]
But it are the graphs on the website and they are not in `plotting.py` hence i putted it on the website repository; but i'll move the issue.

Funny you say bar graphs are too complicated for non-technical users while you use ... a boxplot for the same purpose. If there's something non-technical users don't understand, it's a boxplot.
