### ISSUE TITLE
Date time picker for csv download form

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#38]
The download to csv form (see #24 and #37) has a HTML5 `DateField` (defined in `forms.py`) which renders an automatic date picker in certain browsers, but not all. I would like to change this into a `DateTimeField`, but this has even less built-in support by browsers.

WTForms has support for a `DateTimePickerWidget` (part of `flask_appbuilder.fieldwidgets`) which in turn could use some bootstrap (https://github.com/Eonasdan/bootstrap-datetimepicker). I had no success in implementing it, since bootstrap, js and css are not my strong suit.

Perhaps someone else could take a look?

**Comment by saroele** [comment]
I think a date-picker is enough. Can we close this issue?

**Comment by JrtPec** [comment]
The date picker on the download page seems functional, so we can take it from there if we need it in another place.
