### ISSUE TITLE
Adapt navbar to small screens

### ISSUE THREAD

**Issue by saroele** [opengridcc/website#45]
Probably a bootstrap setting?

**Comment by WolfBerwouts** [comment]
I don't have this problem so difficult to work on. Are you guys using Android?

**Comment by JrtPec** [comment]
Yes, Roel & Karel have Android and have the same problem. It looks like this: 
![img_4678](https://cloud.githubusercontent.com/assets/4570408/12928504/10c7c894-cf6e-11e5-926d-7297ffc4c86a.PNG)
While we would like the collapsed navbar.

**Comment by WolfBerwouts** [comment]
Ow ok, you want to have it collapsed... :)

**Comment by WolfBerwouts** [comment]
We should add a new css file which is only valid for screen sizes with a screen size smaller than... I can try to fix this but only in 4 weeks.

**Comment by JrtPec** [comment]
This should be included in bootstrap, we only need to figure out how to get to these functions.

**Comment by GMathyssen** [comment]
This is fixed, we just need to do a deploy to test it.

**Comment by saroele** [comment]
I have tested locally, works like a charm!  I will deploy today. 
Well done!
