### ISSUE TITLE
Have tables size up on small screens

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#48]

**Comment by GMathyssen** [comment]
Which tables actually?

**Comment by JrtPec** [comment]
I _meant_ the tables on the `data` or `flukso` page. As we added more columns, they became increasingly unreadable on small screens.  I think part of it was already fixed by #45, we also removed the _download to csv_ column in #47. So right now there is no apparent problem.
Let's close for now and I'll reopen the issue when it reappears.
