### ISSUE TITLE
Include graphs per sensor

### ISSUE THREAD

**Issue by dirkdevriendt** [opengridcc/website#5]
_moved from https://github.com/opengridcc/opengrid/issues/35_

Flask website is up at http://95.85.34.168/
Next steps:
- make structure per sensor or per type (electricity, water) and per graph
- add the graphs, as png first?

**Comment by dirkdevriendt** [comment]
Added a very simple NVD3 graph to both one of the IPython notebooks (Demo_WaterGasElekVisualisation) and to a sensor page on the website.

**Comment by saroele** [comment]
I think this can be closed
