### ISSUE TITLE
Add link to discussion group

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#51]
@saroele If you would post the link to the discussion group, maybe a little text surrounding it and an explanations of where on the website you'd like it to be.

**Comment by JrtPec** [comment]
I have spotted the link in opengridcc/opengrid#42

**Comment by saroele** [comment]
Yep, but I'm not sure where to put it.  It seems to me that we have to add it to the `development` tab in another grey box like the one with the github link.  And then we could maybe change the tab name into `feedback` or `get involved` or something?

**Comment by JrtPec** [comment]
Implemented in #52
