### ISSUE TITLE
Brown jumbotron

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#54]
I'm not a big fan of the colour. Thoughts?

**Comment by GMathyssen** [comment]
Maybe change the brown to the same colour as the navbar: #F8F8F8 and the text black again, without shadow.

**Comment by JrtPec** [comment]
Sounds good to me :+1: But since I'm not very good with css and the likes I'll assign you :-)

**Comment by GMathyssen** [comment]
Done, please test it before throwing it on the server. I couldn't test it, I still have trouble running the site locally.

**Comment by JrtPec** [comment]
Done and already online. Please share any problems you might still have.
