### ISSUE TITLE
Pip installed opengrid on server

### ISSUE THREAD

**Issue by JrtPec** [opengridcc/website#67]
@saroele I noticed that the server again runs opengrid installed via pip. We discussed in #12 that this is not useful because it has no config settings. Do you know why this was reinstalled?

Because right now the website cannot initialise a new houseprint, so it defaults to a cached version.

**Comment by saroele** [comment]
Jan,
I did that to be sure to run the website on a released OpenGrid version (note the correct spelling :-) ).
The issue should be easy to solve: we have to put an opengrid.cfg and the passfile in the folder of the website. I did that right now, and I also did a `sudo service uwsgi restart`.  Can you check if it's ok?

**Comment by JrtPec** [comment]
Looks fine. I need to edit the init of the website so it will take the google json from that folder though. I'll prepare a pull request.
