### ISSUE TITLE
two columns on homepage works locally, not on server

### ISSUE THREAD

**Issue by saroele** [opengridcc/website#77]
Anyone can offer some help with this issue?  I have pulled the `gridcamp` branch to the server, but on the homepage, the second flyer is put below the first flyer instead of next to it. 

However, locally this is ok, as shown in the attached screenshot. 

![screenshot - 031716 - 11 49 38](https://cloud.githubusercontent.com/assets/562438/13845037/a52aaa88-ec3d-11e5-9738-e2598e419fef.png)

**Comment by JrtPec** [comment]
I can't seem to replicate the problem. This is opengrid.be as I see it right now (tested on Safari, Chrome and Firefox)

![screen shot 2016-03-17 at 12 45 20](https://cloud.githubusercontent.com/assets/4570408/13845130/272826aa-ec3e-11e5-8a3d-36687dc056c2.png)

**Comment by saroele** [comment]
ha, that's strange but good news. 
indeed, I refreshed the page and now it looks good. 

Um so besser :-)

**Comment by icarus75** [comment]
1/ The side-by-side flyer layout is not responsive. So it won't render well on mobile devices.
2/ The bottom jumbotron is glued to the flyers. Best to add some padding.

**Comment by saroele** [comment]
Padding added.
I don't know how to make it responsive. If someone wants to have  a look, go ahead.
