### ISSUE TITLE
Configure HTTPs with letsencrypt.org

### ISSUE THREAD

**Issue by wouterh** [opengridcc/website#95]
Configure HTTPs on the website using the free certificates from letsencrypt.org.

Prerequisite for #40.

**Comment by wouterh** [comment]
first things first: I installed all available security updates on the droplet. We should reboot the droplet now. Anyone against rebooting the droplet somewhere in the near future?

**Comment by wouterh** [comment]
HTTPs is now configured (see also 0766fb3f8b6b7e75c73fd4a9dbbc69e946dca30b). The certificates of let's encrypt are only valid for 90 days, so automatic renewal is key. I still have to set that up, so I'll leave this issue open.

**Comment by JrtPec** [comment]
The login page is live! Please check it out with your own credentials...

**Comment by saroele** [comment]
I can login (happens automatically by allowing the site to access my github account). 
After loggin in, I get this flash message `Welcome, saroele. Become an OpenGrid contributor to view all restricted pages`.  Is this normal?  I think I contributed already ;-)

**Comment by wouterh** [comment]
I get `Welcome, wouterh. Thanks for contributing to OpenGrid!`. I guess it doesn't work because you have another role on github. You are the opengridcc owner, right?

**Comment by JrtPec** [comment]
It checks if you have OpenGrid among your forks. I guess Roel must be a special case…

On Tue, 05 Apr 2016 at 08:36 "Wouter Horré"

<
mailto:

> wrote:

I get

Welcome, wouterh. Thanks for contributing to OpenGrid!

. I guess it doesn't work because you have another role on github. You are the opengridcc owner, right?

**Comment by saroele** [comment]
ok, i'll fork it to my account then.  Good practice anyway :-)

**Comment by wouterh** [comment]
hmm, that makes it very easy for a random person to get access to the private parts of the website, no? Everybody can fork the opengrid repository to its personal account.

Isn't there a way to check whether someone is an opengridcc member?

**Comment by wouterh** [comment]
FYI, I mostly followed this tutorial for setting up HTTPs: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

**Comment by wouterh** [comment]
Automatic renewal is now in place. We'll see in june :-)
